### ISSUE TITLE
Small changes

### ISSUE THREAD

**Issue by ofirbs** [Refa90/Shauli#1]
**Tasks:**

- [ ] 1. do not show the image / video if there is no image / video in the blog page
- [ ] 2. In the Fans club, why is the gender a checkbox? Shouldnt it be a string?
- [ ] 3. in the Details of a post, we should add some style: underline the headlines, and make the comments clearer.
- [x] 4. add '|' between "Delete" and "Comments" in the manage page
- [x] 5. Should we change the "Mange Posts" link to a tab (replace the About tab)
- [x] 6. we should remove the DropCreateDatabaseAlways. We need to keep the database. (It should work without this function)
~~7. Add my function that shows how many "number of posts comments" are accually chosen in the search section~~
- [ ] 8. chang the style of the posts (seperate them)
- [ ] 9. change the Loren Ipsum shit
- [ ] 10. expand the Posts/Index table to the whole page. (like our table)
- [ ] 11. insert the search forms to a table for nicer style
- [ ] 14. put the facebook buttons in Layout and style it.
